/** @type {import('tailwindcss').Config} */
module.exports = {
  // NativeWind 4.2+ on web needs class mode so colorScheme.set doesn't crash.
  darkMode: 'class',
  // NOTE: Update this to include the paths to all files that contain Nativewind classes.
  content: ['./app/**/*.{js,jsx,ts,tsx}', './src/**/*.{js,jsx,ts,tsx}'],
  presets: [require('nativewind/preset')],
  theme: {
    extend: {
      fontSize: {
        // Figma micro sizes used across native screens
        '2xs': '8.96px',
        caption: '11.2px',
        xs: '12px',
        sm: '14px',
        base: '16px',
        md: '17px',
        lg: '18px',
        xl: '20px',
        'heading-sm': '21.88px',
        '2xl': '24px',
        heading: '27.34px',
        '3xl': '30px',
        '4xl': '36px',
        '5xl': '48px',
        '6xl': '60px',
        '7xl': '72px',
        '8xl': '96px',
        '9xl': '128px',
      },

      fontFamily: {
        'ubuntu-extralight': ['UbuntuSans-ExtraLight', 'system-ui'],
        'ubuntu-light': ['UbuntuSans-Light', 'system-ui'],
        'ubuntu-regular': ['UbuntuSans-Regular', 'system-ui'],
        'ubuntu-medium': ['UbuntuSans-Medium', 'system-ui'],
        'ubuntu-semibold': ['UbuntuSans-SemiBold', 'system-ui'],
        'ubuntu-bold': ['UbuntuSans-Bold', 'system-ui'],
        'ubuntu-extrabold': ['UbuntuSans-ExtraBold', 'system-ui'],
        'ubuntu-italic': ['UbuntuSansItalic', 'system-ui'],
        'roboto-italic': ['RobotoItalic', 'system-ui'],
        'roboto-regular': ['Roboto', 'system-ui'],
        'inter-extralight': ['Inter_18pt-ExtraLight', 'system-ui'],
        'inter-light': ['Inter_18pt-Light', 'system-ui'],
        'inter-regular': ['Inter_18pt-Regular', 'system-ui'],
        'inter-medium': ['Inter_18pt-Medium', 'system-ui'],
        'inter-medium-italic': ['Inter_18pt-mediumItalic', 'system-ui'],
        'inter-semibold': ['Inter_18pt-SemiBold', 'system-ui'],
        roboto: ['Roboto', 'system-ui'],
        UbuntuSans: ['"UbuntuSans"', 'system-ui'],
        UbuntuSansItalic: ['"UbuntuSansItalic"', 'system-ui'],
        Inter: ['"Inter"', 'system-ui'],
      },

      colors: {
        primary: '#113E55',
        secondary: '#1E40AF',
        accent: '#CEE5ED',
        orange: '#F46036',
        teal: '#1B998B',
        grey: '#9B9797',
        tertiary: '#F46036',
        'light-orange': '#FFF8F5',
        'light-teal': '#F4FFFE',
        'light-grey': '#F7F9F9',
        'dark-teal': '#167a6f',
        body: '#FBFEFF',
        'input-border': '#D1D5DB',
        danger: '#ED0808',
        black: '#04121A',
      },

      borderWidth: {
        micro: '0.1px',
        mini: '0.5px',
      },
    },
  },
  plugins: [],
};
